name:                Aoc2018
version:             0.1.0.0
github:              "filedesles/Aoc2018"
license:             MIT
author:              "filedesless"
maintainer:          "filedesless@thehacker.space"
copyright:           "2018 filedesless"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/filedesless/Aoc2018#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- text
- split
- time
- deque
- hspec
- QuickCheck
- criterion
- vector
- array

library:
  source-dirs: src

executables:
  Aoc2018-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Aoc2018

tests:
  Aoc2018-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Aoc2018

benchmarks:
  Aoc2018-bench:
    main:                Main.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Aoc2018
