name:                Aoc2019
version:             0.1.0.0
github:              "filedesles/Aoc2019"
license:             MIT
author:              "filedesless"
maintainer:          "filedesless"
copyright:           "2019 filedesless"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/filedesless/Aoc2019#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- QuickCheck
- containers
- mtl
- split
- directory

library:
  source-dirs: src

executables:
  Aoc2019-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Aoc2019

tests:
  Aoc2019-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Aoc2019
